/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Do not edit this file directly.
*/
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => NoteSparkPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/settings.ts
var DEFAULT_SETTINGS = {
  apiKey: "",
  model: "mistral-small-latest",
  temperature: 0.7,
  maxTokens: 120,
  requestTimeoutMs: 2e4,
  defaultPrompt: "Generate one concise, original quote or reflection for a daily note. Keep it grounded, memorable, and useful.",
  defaultMaxLength: 140,
  outputMode: "callout",
  defaultCalloutType: "quote",
  autoGenerate: true,
  templateFolderPath: "",
  presets: [
    {
      id: 1,
      prompt: "Generate a motivational quote for studying.",
      maxLength: 120,
      calloutType: "quote"
    },
    {
      id: 2,
      prompt: "Generate a calm reflection for journaling.",
      maxLength: 180,
      calloutType: "quote"
    },
    {
      id: 3,
      prompt: "Generate a productivity-focused quote.",
      maxLength: 100,
      calloutType: "quote"
    }
  ]
};
function normalizeSettings(data) {
  const raw = data != null ? data : {};
  return {
    ...DEFAULT_SETTINGS,
    ...raw,
    apiKey: typeof raw.apiKey === "string" ? raw.apiKey : DEFAULT_SETTINGS.apiKey,
    model: normalizeString(raw.model, DEFAULT_SETTINGS.model),
    temperature: clampNumber(raw.temperature, 0, 2, DEFAULT_SETTINGS.temperature),
    maxTokens: clampInteger(raw.maxTokens, 1, 4096, DEFAULT_SETTINGS.maxTokens),
    requestTimeoutMs: clampInteger(
      raw.requestTimeoutMs,
      1e3,
      12e4,
      DEFAULT_SETTINGS.requestTimeoutMs
    ),
    defaultPrompt: normalizeString(raw.defaultPrompt, DEFAULT_SETTINGS.defaultPrompt),
    defaultMaxLength: clampInteger(
      raw.defaultMaxLength,
      1,
      2e3,
      DEFAULT_SETTINGS.defaultMaxLength
    ),
    outputMode: raw.outputMode === "plain" ? "plain" : "callout",
    defaultCalloutType: normalizeCalloutType(
      raw.defaultCalloutType,
      DEFAULT_SETTINGS.defaultCalloutType
    ),
    autoGenerate: typeof raw.autoGenerate === "boolean" ? raw.autoGenerate : true,
    templateFolderPath: normalizeFolderPath(raw.templateFolderPath),
    presets: normalizePresets(raw.presets)
  };
}
function resolvePrompt(settings, presetId) {
  if (presetId === void 0) {
    return {
      label: "Default prompt",
      prompt: settings.defaultPrompt,
      maxLength: settings.defaultMaxLength,
      calloutType: settings.defaultCalloutType
    };
  }
  const preset = settings.presets.find((item) => item.id === presetId);
  if (!preset) {
    return null;
  }
  return {
    id: preset.id,
    label: `Preset ${preset.id}`,
    prompt: preset.prompt,
    maxLength: preset.maxLength,
    calloutType: preset.calloutType
  };
}
function getPromptChoices(settings) {
  return [
    resolvePrompt(settings),
    ...settings.presets.slice().sort((a, b) => a.id - b.id).map((preset) => ({
      id: preset.id,
      label: `Preset ${preset.id}`,
      prompt: preset.prompt,
      maxLength: preset.maxLength,
      calloutType: preset.calloutType
    }))
  ];
}
function normalizeCalloutType(value, fallback = "quote") {
  if (typeof value !== "string") {
    return fallback;
  }
  const trimmed = value.trim();
  if (!trimmed) {
    return fallback;
  }
  const normalized = trimmed.replace(/[^A-Za-z0-9_-]/g, "-").replace(/-+/g, "-").replace(/^-+|-+$/g, "");
  return normalized || fallback;
}
function normalizeFolderPath(value) {
  if (typeof value !== "string") {
    return "";
  }
  return value.trim().replace(/\\/g, "/").replace(/\/+/g, "/").replace(/^\/+|\/+$/g, "");
}
function isFileInTemplateFolder(filePath, templateFolderPath) {
  const folderPath = normalizeFolderPath(templateFolderPath);
  const normalizedFilePath = normalizeFolderPath(filePath);
  if (!folderPath || !normalizedFilePath) {
    return false;
  }
  return normalizedFilePath === folderPath || normalizedFilePath.startsWith(`${folderPath}/`);
}
function normalizePresets(value) {
  if (!Array.isArray(value)) {
    return DEFAULT_SETTINGS.presets;
  }
  const seen = /* @__PURE__ */ new Set();
  const presets = [];
  for (const item of value) {
    if (!item || typeof item !== "object") {
      continue;
    }
    const rawPreset = item;
    const id = clampInteger(rawPreset.id, 1, 9999, 0);
    const prompt = normalizeString(rawPreset.prompt, "");
    if (!id || !prompt || seen.has(id)) {
      continue;
    }
    seen.add(id);
    presets.push({
      id,
      prompt,
      maxLength: clampInteger(rawPreset.maxLength, 1, 2e3, 140),
      calloutType: typeof rawPreset.calloutType === "string" && rawPreset.calloutType.trim() ? normalizeCalloutType(rawPreset.calloutType) : void 0
    });
  }
  return presets.sort((a, b) => a.id - b.id);
}
function normalizeString(value, fallback) {
  if (typeof value !== "string") {
    return fallback;
  }
  const trimmed = value.trim();
  return trimmed || fallback;
}
function clampInteger(value, min, max, fallback) {
  if (typeof value !== "number" || !Number.isFinite(value)) {
    return fallback;
  }
  return Math.min(max, Math.max(min, Math.round(value)));
}
function clampNumber(value, min, max, fallback) {
  if (typeof value !== "number" || !Number.isFinite(value)) {
    return fallback;
  }
  return Math.min(max, Math.max(min, value));
}

// src/output.ts
function cleanGeneratedText(text, maxLength) {
  const normalized = text.replace(/\r\n/g, "\n").replace(/^```[\s\S]*?\n/, "").replace(/\n```$/, "").split("\n").map((line) => line.replace(/^\s*>\s?/, "").trimEnd()).join("\n").trim();
  if (normalized.length <= maxLength) {
    return normalized;
  }
  return normalized.slice(0, maxLength).trimEnd();
}
function formatOutput(generatedText, settings, prompt) {
  const text = cleanGeneratedText(generatedText, prompt.maxLength);
  if (settings.outputMode === "plain") {
    return text;
  }
  const calloutType = normalizeCalloutType(prompt.calloutType, settings.defaultCalloutType);
  const quoteLines = text.split("\n").map((line) => `> ${line}`);
  return [`> [!${calloutType}]`, ...quoteLines].join("\n");
}

// src/mistralClient.ts
var NoteSparkGenerationError = class extends Error {
  constructor(message) {
    super(message);
    this.name = "NoteSparkGenerationError";
  }
};
async function generateQuote(settings, prompt, requester) {
  if (!settings.apiKey.trim()) {
    throw new NoteSparkGenerationError("Add a Mistral API key in NoteSpark settings first.");
  }
  const response = await withTimeout(
    requester({
      url: "https://api.mistral.ai/v1/chat/completions",
      method: "POST",
      headers: {
        Authorization: `Bearer ${settings.apiKey.trim()}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        model: settings.model,
        temperature: settings.temperature,
        max_tokens: settings.maxTokens,
        stream: false,
        messages: [
          {
            role: "system",
            content: "You generate concise, original quotes, reflections, or writing prompts. Return only the final text. Do not include markdown, labels, explanations, or surrounding quotation marks."
          },
          {
            role: "user",
            content: `${prompt.prompt}

Keep the answer within ${prompt.maxLength} characters.`
          }
        ]
      })
    }),
    settings.requestTimeoutMs
  );
  if (response.status < 200 || response.status >= 300) {
    throw new NoteSparkGenerationError(getErrorMessage(response));
  }
  const content = extractContent(response.json);
  if (!content.trim()) {
    throw new NoteSparkGenerationError("Mistral response did not include generated content.");
  }
  return cleanGeneratedText(content, prompt.maxLength);
}
function extractContent(data) {
  var _a, _b, _c;
  const response = data;
  const content = (_c = (_b = (_a = response.choices) == null ? void 0 : _a[0]) == null ? void 0 : _b.message) == null ? void 0 : _c.content;
  if (typeof content === "string") {
    return content;
  }
  if (Array.isArray(content)) {
    return content.map((chunk) => {
      if (chunk.type && chunk.type !== "text") {
        return "";
      }
      return typeof chunk.text === "string" ? chunk.text : "";
    }).join("");
  }
  return "";
}
function getErrorMessage(response) {
  var _a;
  const json = response.json;
  if (typeof (json == null ? void 0 : json.error) === "string") {
    return `Mistral request failed: ${json.error}`;
  }
  if (typeof ((_a = json == null ? void 0 : json.error) == null ? void 0 : _a.message) === "string") {
    return `Mistral request failed: ${json.error.message}`;
  }
  if (typeof (json == null ? void 0 : json.message) === "string") {
    return `Mistral request failed: ${json.message}`;
  }
  return `Mistral request failed with HTTP ${response.status}.`;
}
async function withTimeout(promise, timeoutMs) {
  let timeoutHandle;
  const timeout = new Promise((_, reject) => {
    timeoutHandle = setTimeout(() => {
      reject(new NoteSparkGenerationError(`Mistral request timed out after ${timeoutMs} ms.`));
    }, timeoutMs);
  });
  try {
    return await Promise.race([promise, timeout]);
  } catch (error) {
    if (error instanceof NoteSparkGenerationError) {
      throw error;
    }
    const message = error instanceof Error ? error.message : "Unknown network error.";
    throw new NoteSparkGenerationError(`Mistral request failed: ${message}`);
  } finally {
    if (timeoutHandle) {
      clearTimeout(timeoutHandle);
    }
  }
}

// src/regenerateModal.ts
var import_obsidian = require("obsidian");
var PromptPickerModal = class extends import_obsidian.SuggestModal {
  constructor(app, prompts, onChoosePrompt) {
    super(app);
    this.prompts = prompts;
    this.onChoosePrompt = onChoosePrompt;
    this.setPlaceholder("Choose a NoteSpark prompt");
  }
  getSuggestions(query) {
    const normalizedQuery = query.trim().toLowerCase();
    if (!normalizedQuery) {
      return this.prompts;
    }
    return this.prompts.filter((prompt) => {
      const id = prompt.id === void 0 ? "default" : String(prompt.id);
      return prompt.label.toLowerCase().includes(normalizedQuery) || id.includes(normalizedQuery) || prompt.prompt.toLowerCase().includes(normalizedQuery);
    });
  }
  renderSuggestion(prompt, el) {
    el.createDiv({ text: prompt.label, cls: "notespark-suggestion-title" });
    el.createDiv({ text: prompt.prompt, cls: "notespark-suggestion-prompt" });
  }
  onChooseSuggestion(prompt) {
    void this.onChoosePrompt(prompt);
  }
};

// src/settingsTab.ts
var import_obsidian2 = require("obsidian");
var NoteSparkSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(plugin) {
    super(plugin.app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.addClass("notespark-settings");
    containerEl.createEl("h2", { text: "NoteSpark" });
    new import_obsidian2.Setting(containerEl).setName("Mistral API key").setDesc("Stored locally in this vault's plugin data.").addText((text) => {
      text.inputEl.type = "password";
      text.setPlaceholder("Mistral API key").setValue(this.plugin.settings.apiKey).onChange(async (value) => {
        this.plugin.settings.apiKey = value.trim();
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian2.Setting(containerEl).setName("Model").addText(
      (text) => text.setValue(this.plugin.settings.model).onChange(async (value) => {
        this.plugin.settings.model = value.trim() || "mistral-small-latest";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Temperature").setDesc("Higher values produce more varied output.").addSlider(
      (slider) => slider.setLimits(0, 2, 0.1).setValue(this.plugin.settings.temperature).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.temperature = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Max output tokens").addText(
      (text) => text.setValue(String(this.plugin.settings.maxTokens)).onChange(async (value) => {
        this.plugin.settings.maxTokens = parseInteger(value, this.plugin.settings.maxTokens);
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Request timeout").setDesc("Milliseconds before a Mistral request is treated as failed.").addText(
      (text) => text.setValue(String(this.plugin.settings.requestTimeoutMs)).onChange(async (value) => {
        this.plugin.settings.requestTimeoutMs = parseInteger(
          value,
          this.plugin.settings.requestTimeoutMs
        );
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "Default prompt" });
    new import_obsidian2.Setting(containerEl).setName("Prompt").addTextArea((text) => {
      text.inputEl.rows = 4;
      text.setValue(this.plugin.settings.defaultPrompt).onChange(async (value) => {
        this.plugin.settings.defaultPrompt = value.trim();
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian2.Setting(containerEl).setName("Maximum quote length").addText(
      (text) => text.setValue(String(this.plugin.settings.defaultMaxLength)).onChange(async (value) => {
        this.plugin.settings.defaultMaxLength = parseInteger(
          value,
          this.plugin.settings.defaultMaxLength
        );
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "Output" });
    new import_obsidian2.Setting(containerEl).setName("Output mode").addDropdown(
      (dropdown) => dropdown.addOption("callout", "Obsidian callout").addOption("plain", "Plain text").setValue(this.plugin.settings.outputMode).onChange(async (value) => {
        this.plugin.settings.outputMode = value === "plain" ? "plain" : "callout";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Default callout type").addText(
      (text) => text.setValue(this.plugin.settings.defaultCalloutType).onChange(async (value) => {
        this.plugin.settings.defaultCalloutType = normalizeCalloutType(value);
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Auto-generate in active markdown files").setDesc("Replaces standalone @notespark triggers after templates or manual typing add them.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoGenerate).onChange(async (value) => {
        this.plugin.settings.autoGenerate = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Template folder to ignore").setDesc("Vault-relative folder path. NoteSpark will not generate inside this folder, but daily notes created from templates still generate outside it.").addText(
      (text) => text.setPlaceholder("Templates").setValue(this.plugin.settings.templateFolderPath).onChange(async (value) => {
        this.plugin.settings.templateFolderPath = normalizeFolderPath(value);
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "Prompt presets" });
    const presetContainer = containerEl.createDiv({ cls: "notespark-presets" });
    for (const preset of this.plugin.settings.presets) {
      this.renderPreset(presetContainer, preset);
    }
    new import_obsidian2.Setting(containerEl).addButton(
      (button) => button.setButtonText("Add preset").setCta().onClick(async () => {
        this.plugin.settings.presets.push({
          id: getNextPresetId(this.plugin.settings.presets),
          prompt: "Generate a concise reflection.",
          maxLength: 140,
          calloutType: "quote"
        });
        await this.plugin.saveSettings();
        this.display();
      })
    );
  }
  renderPreset(containerEl, preset) {
    const presetEl = containerEl.createDiv({ cls: "notespark-preset" });
    const header = presetEl.createDiv({ cls: "notespark-preset-header" });
    header.createEl("strong", { text: `Preset ${preset.id}` });
    const deleteButton = header.createEl("button", { text: "Remove" });
    deleteButton.addEventListener("click", async () => {
      this.plugin.settings.presets = this.plugin.settings.presets.filter(
        (item) => item !== preset
      );
      await this.plugin.saveSettings();
      this.display();
    });
    new import_obsidian2.Setting(presetEl).setName("ID").addText(
      (text) => text.setValue(String(preset.id)).onChange(async (value) => {
        preset.id = parseInteger(value, preset.id);
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(presetEl).setName("Prompt").addTextArea((text) => {
      text.inputEl.rows = 3;
      text.setValue(preset.prompt).onChange(async (value) => {
        preset.prompt = value.trim();
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian2.Setting(presetEl).setName("Maximum quote length").addText(
      (text) => text.setValue(String(preset.maxLength)).onChange(async (value) => {
        preset.maxLength = parseInteger(value, preset.maxLength);
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(presetEl).setName("Callout type").setDesc("Leave empty to use the global default.").addText(
      (text) => {
        var _a;
        return text.setValue((_a = preset.calloutType) != null ? _a : "").onChange(async (value) => {
          preset.calloutType = value.trim() ? normalizeCalloutType(value) : void 0;
          await this.plugin.saveSettings();
        });
      }
    );
  }
};
function parseInteger(value, fallback) {
  const parsed = Number.parseInt(value, 10);
  return Number.isFinite(parsed) && parsed > 0 ? parsed : fallback;
}
function getNextPresetId(presets) {
  return presets.reduce((highest, preset) => Math.max(highest, preset.id), 0) + 1;
}

// src/trigger.ts
var TRIGGER_PATTERN = /^@notespark(?:\[(\d+)])?$/;
function findNoteSparkTriggers(content) {
  var _a;
  const triggers = [];
  const lines = content.split("\n");
  let offset = 0;
  let fence = null;
  for (let lineNumber = 0; lineNumber < lines.length; lineNumber += 1) {
    const rawLine = (_a = lines[lineNumber]) != null ? _a : "";
    const line = rawLine.endsWith("\r") ? rawLine.slice(0, -1) : rawLine;
    const fenceDelimiter = getFenceDelimiter(line);
    if (fenceDelimiter) {
      if (!fence) {
        fence = fenceDelimiter;
      } else if (fence.marker === fenceDelimiter.marker && fenceDelimiter.length >= fence.length) {
        fence = null;
      }
      offset += rawLine.length + (lineNumber < lines.length - 1 ? 1 : 0);
      continue;
    }
    if (!fence) {
      const trimmed = line.trim();
      const match = trimmed.match(TRIGGER_PATTERN);
      if (match) {
        triggers.push({
          start: offset,
          end: offset + line.length,
          line: lineNumber,
          raw: trimmed,
          presetId: match[1] ? Number(match[1]) : void 0
        });
      }
    }
    offset += rawLine.length + (lineNumber < lines.length - 1 ? 1 : 0);
  }
  return triggers;
}
function hasNoteSparkTrigger(content) {
  return findNoteSparkTriggers(content).length > 0;
}
function offsetToPosition(content, offset) {
  const boundedOffset = Math.max(0, Math.min(content.length, offset));
  let line = 0;
  let lineStart = 0;
  for (let index = 0; index < boundedOffset; index += 1) {
    if (content.charCodeAt(index) === 10) {
      line += 1;
      lineStart = index + 1;
    }
  }
  return {
    line,
    ch: boundedOffset - lineStart
  };
}
function getFenceDelimiter(line) {
  const match = line.match(/^\s*(`{3,}|~{3,})/);
  if (!match) {
    return null;
  }
  const token = match[1];
  return {
    marker: token[0],
    length: token.length
  };
}

// src/main.ts
var NoteSparkPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.autoGenerateTimer = null;
    this.processingFiles = /* @__PURE__ */ new Set();
  }
  async onload() {
    this.settings = normalizeSettings(await this.loadData());
    this.addSettingTab(new NoteSparkSettingTab(this));
    this.addCommand({
      id: "generate-active-note",
      name: "Generate triggers in active note",
      editorCallback: async (editor, view) => {
        if (!view.file) {
          new import_obsidian3.Notice("Open a markdown note before generating NoteSpark triggers.");
          return;
        }
        await this.replaceTriggersInEditor(editor, view, false);
      }
    });
    this.addCommand({
      id: "regenerate-quote",
      name: "Regenerate quote",
      editorCallback: (editor, view) => {
        if (view.file && this.shouldIgnoreFile(view.file)) {
          new import_obsidian3.Notice("NoteSpark is disabled inside the configured template folder.");
          return;
        }
        this.openRegeneratePromptPicker(editor);
      }
    });
    this.registerEvent(
      this.app.workspace.on("file-open", () => {
        this.scheduleActiveFileGeneration();
      })
    );
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", () => {
        this.scheduleActiveFileGeneration();
      })
    );
    this.registerEvent(
      this.app.workspace.on("editor-change", (editor, view) => {
        if (view.file) {
          this.scheduleAutoGeneration(editor, view);
        }
      })
    );
    this.app.workspace.onLayoutReady(() => {
      this.scheduleActiveFileGeneration();
    });
  }
  onunload() {
    if (this.autoGenerateTimer) {
      clearTimeout(this.autoGenerateTimer);
      this.autoGenerateTimer = null;
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  scheduleActiveFileGeneration() {
    const view = this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
    if (!view) {
      return;
    }
    this.scheduleAutoGeneration(view.editor, view);
  }
  scheduleAutoGeneration(editor, view) {
    if (!this.settings.autoGenerate || !view.file || !hasNoteSparkTrigger(editor.getValue())) {
      return;
    }
    if (this.shouldIgnoreFile(view.file)) {
      return;
    }
    if (this.autoGenerateTimer) {
      clearTimeout(this.autoGenerateTimer);
    }
    this.autoGenerateTimer = setTimeout(() => {
      void this.replaceTriggersInEditor(editor, view, true);
    }, 1e3);
  }
  async replaceTriggersInEditor(editor, view, automatic) {
    const fileKey = getFileKey(view.file);
    if (view.file && this.shouldIgnoreFile(view.file)) {
      if (!automatic) {
        new import_obsidian3.Notice("NoteSpark is disabled inside the configured template folder.");
      }
      return;
    }
    if (this.processingFiles.has(fileKey)) {
      if (!automatic) {
        new import_obsidian3.Notice("NoteSpark is already generating for this note.");
      }
      return;
    }
    const originalContent = editor.getValue();
    const triggers = findNoteSparkTriggers(originalContent);
    if (triggers.length === 0) {
      if (!automatic) {
        new import_obsidian3.Notice("No NoteSpark triggers found in the active note.");
      }
      return;
    }
    this.processingFiles.add(fileKey);
    try {
      const replacements = [];
      const prompts = triggers.map((trigger) => {
        const prompt = resolvePrompt(this.settings, trigger.presetId);
        if (!prompt) {
          throw new NoteSparkGenerationError(`No NoteSpark preset exists with ID ${trigger.presetId}.`);
        }
        return { trigger, prompt };
      });
      for (const { trigger, prompt } of prompts) {
        const generated = await generateQuote(this.settings, prompt, import_obsidian3.requestUrl);
        replacements.push({
          start: trigger.start,
          end: trigger.end,
          text: formatOutput(generated, this.settings, prompt)
        });
      }
      if (editor.getValue() !== originalContent) {
        throw new NoteSparkGenerationError("The note changed before NoteSpark could insert text.");
      }
      applyReplacements(editor, originalContent, replacements);
      if (!automatic) {
        new import_obsidian3.Notice(`Generated ${replacements.length} NoteSpark ${replacements.length === 1 ? "entry" : "entries"}.`);
      }
    } catch (error) {
      new import_obsidian3.Notice(getGenerationErrorMessage(error));
    } finally {
      this.processingFiles.delete(fileKey);
    }
  }
  shouldIgnoreFile(file) {
    return isFileInTemplateFolder(file.path, this.settings.templateFolderPath);
  }
  openRegeneratePromptPicker(editor) {
    const prompts = getPromptChoices(this.settings);
    new PromptPickerModal(this.app, prompts, async (prompt) => {
      await this.regenerateTarget(editor, prompt);
    }).open();
  }
  async regenerateTarget(editor, prompt) {
    const originalContent = editor.getValue();
    const target = getRegenerationTarget(editor);
    if (!target) {
      new import_obsidian3.Notice("Select text or place the cursor inside an Obsidian callout to regenerate it.");
      return;
    }
    try {
      const generated = await generateQuote(this.settings, prompt, import_obsidian3.requestUrl);
      const output = formatOutput(generated, this.settings, prompt);
      if (editor.getValue() !== originalContent) {
        throw new NoteSparkGenerationError("The note changed before NoteSpark could insert text.");
      }
      editor.replaceRange(output, target.from, target.to);
      new import_obsidian3.Notice("Regenerated NoteSpark entry.");
    } catch (error) {
      new import_obsidian3.Notice(getGenerationErrorMessage(error));
    }
  }
};
function applyReplacements(editor, originalContent, replacements) {
  for (const replacement of replacements.slice().sort((a, b) => b.start - a.start)) {
    editor.replaceRange(
      replacement.text,
      offsetToPosition(originalContent, replacement.start),
      offsetToPosition(originalContent, replacement.end)
    );
  }
}
function getRegenerationTarget(editor) {
  const selection = editor.getSelection();
  if (selection.trim()) {
    const from = editor.getCursor("from");
    const to = editor.getCursor("to");
    return { from, to };
  }
  return getCurrentCalloutTarget(editor);
}
function getCurrentCalloutTarget(editor) {
  const cursor = editor.getCursor();
  const lineCount = editor.lineCount();
  const currentLine = editor.getLine(cursor.line);
  if (!isBlockquoteLine(currentLine)) {
    return null;
  }
  let startLine = cursor.line;
  while (startLine > 0 && isBlockquoteLine(editor.getLine(startLine - 1))) {
    startLine -= 1;
  }
  if (!/^\s*>\s*\[!/.test(editor.getLine(startLine))) {
    return null;
  }
  let endLine = cursor.line;
  while (endLine + 1 < lineCount && isBlockquoteLine(editor.getLine(endLine + 1))) {
    endLine += 1;
  }
  return {
    from: { line: startLine, ch: 0 },
    to: { line: endLine, ch: editor.getLine(endLine).length }
  };
}
function isBlockquoteLine(line) {
  return /^\s*>\s?/.test(line);
}
function getFileKey(file) {
  var _a;
  return (_a = file == null ? void 0 : file.path) != null ? _a : "__active_note__";
}
function getGenerationErrorMessage(error) {
  if (error instanceof Error) {
    return error.message;
  }
  return "NoteSpark generation failed.";
}
